name: Docker Image Conda

on:
  push:
    paths:
      - 'workflows/docker_image_conda.yml'
      - 'Dockerfile'
      - 'requirements.txt' 
      
env:
  DOCKER_REPO: miniconda_img

jobs:
  Build_Docker_Image:
    runs-on: continuumio/miniconda3
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: Login Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    - name: Build image
      run: docker build . --file Dockerfile --tag $DOCKER_REPO

    - name: Push image
      run: docker push $DOCKER_REPO

    - name: Push image with date
      run: |
        DATE=$(date +'%Y%m%d')
        docker tag $DOCKER_REPO $DOCKER_REPO:build.$DATE
        docker push $DOCKER_REPO:build.$DATE
    - name: Push image with git commit hash
      run: |
        docker tag $DOCKER_REPO $DOCKER_REPO:${GITHUB_SHA::7}
        docker push $DOCKER_REPO:${GITHUB_SHA::7}
